//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 03:50:55 PM CEST 
//


package com.thalesgroup.optet.common.jaxb.TWProfile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thalesgroup.optet.common.jaxb.TWProfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thalesgroup.optet.common.jaxb.TWProfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TWProfile }
     * 
     */
    public TWProfile createTWProfile() {
        return new TWProfile();
    }

    /**
     * Create an instance of {@link TWProfile.TWAttribute }
     * 
     */
    public TWProfile.TWAttribute createTWProfileTWAttribute() {
        return new TWProfile.TWAttribute();
    }

    /**
     * Create an instance of {@link TWProfile.TWAttribute.Metric }
     * 
     */
    public TWProfile.TWAttribute.Metric createTWProfileTWAttributeMetric() {
        return new TWProfile.TWAttribute.Metric();
    }

}
