//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 03:50:55 PM CEST 
//


package com.thalesgroup.optet.common.jaxb.TWProfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TWAttribute" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Metric" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="metricID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="attributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "twAttribute"
})
@XmlRootElement(name = "TWProfile")
public class TWProfile {

    @XmlElement(name = "TWAttribute")
    protected List<TWProfile.TWAttribute> twAttribute;

    /**
     * Gets the value of the twAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the twAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTWAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TWProfile.TWAttribute }
     * 
     * 
     */
    public List<TWProfile.TWAttribute> getTWAttribute() {
        if (twAttribute == null) {
            twAttribute = new ArrayList<TWProfile.TWAttribute>();
        }
        return this.twAttribute;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Metric" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="metricID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="attributeID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "metric"
    })
    public static class TWAttribute {

        @XmlElement(name = "Metric")
        protected List<TWProfile.TWAttribute.Metric> metric;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "attributeID")
        protected String attributeID;
        @XmlAttribute(name = "expectedValue")
        protected String expectedValue;

        /**
         * Gets the value of the metric property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metric property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMetric().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TWProfile.TWAttribute.Metric }
         * 
         * 
         */
        public List<TWProfile.TWAttribute.Metric> getMetric() {
            if (metric == null) {
                metric = new ArrayList<TWProfile.TWAttribute.Metric>();
            }
            return this.metric;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the attributeID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAttributeID() {
            return attributeID;
        }

        /**
         * Sets the value of the attributeID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAttributeID(String value) {
            this.attributeID = value;
        }

        /**
         * Gets the value of the expectedValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpectedValue() {
            return expectedValue;
        }

        /**
         * Sets the value of the expectedValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpectedValue(String value) {
            this.expectedValue = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="metricID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="expectedValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Metric {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "metricID")
            protected String metricID;
            @XmlAttribute(name = "expectedValue")
            protected String expectedValue;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the metricID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMetricID() {
                return metricID;
            }

            /**
             * Sets the value of the metricID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMetricID(String value) {
                this.metricID = value;
            }

            /**
             * Gets the value of the expectedValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExpectedValue() {
                return expectedValue;
            }

            /**
             * Sets the value of the expectedValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExpectedValue(String value) {
                this.expectedValue = value;
            }

        }

    }

}
