//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.31 at 04:40:48 PM CEST 
//


package com.thalesgroup.optet.common.jaxb.optet;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thalesgroup.optet.common.jaxb.optet package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Optet_QNAME = new QName("", "optet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thalesgroup.optet.common.jaxb.optet
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OptetType }
     * 
     */
    public OptetType createOptetType() {
        return new OptetType();
    }

    /**
     * Create an instance of {@link OptetType.Audits }
     * 
     */
    public OptetType.Audits createOptetTypeAudits() {
        return new OptetType.Audits();
    }

    /**
     * Create an instance of {@link OptetType.Audits.File }
     * 
     */
    public OptetType.Audits.File createOptetTypeAuditsFile() {
        return new OptetType.Audits.File();
    }

    /**
     * Create an instance of {@link OptetType.Metrics }
     * 
     */
    public OptetType.Metrics createOptetTypeMetrics() {
        return new OptetType.Metrics();
    }

    /**
     * Create an instance of {@link OptetType.TestResults }
     * 
     */
    public OptetType.TestResults createOptetTypeTestResults() {
        return new OptetType.TestResults();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage }
     * 
     */
    public OptetType.TestCoverage createOptetTypeTestCoverage() {
        return new OptetType.TestCoverage();
    }

    /**
     * Create an instance of {@link OptetType.Audits.File.Violation }
     * 
     */
    public OptetType.Audits.File.Violation createOptetTypeAuditsFileViolation() {
        return new OptetType.Audits.File.Violation();
    }

    /**
     * Create an instance of {@link OptetType.Metrics.Metric }
     * 
     */
    public OptetType.Metrics.Metric createOptetTypeMetricsMetric() {
        return new OptetType.Metrics.Metric();
    }

    /**
     * Create an instance of {@link OptetType.TestResults.TestResult }
     * 
     */
    public OptetType.TestResults.TestResult createOptetTypeTestResultsTestResult() {
        return new OptetType.TestResults.TestResult();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage.Classes }
     * 
     */
    public OptetType.TestCoverage.Classes createOptetTypeTestCoverageClasses() {
        return new OptetType.TestCoverage.Classes();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage.Methods }
     * 
     */
    public OptetType.TestCoverage.Methods createOptetTypeTestCoverageMethods() {
        return new OptetType.TestCoverage.Methods();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage.Lines }
     * 
     */
    public OptetType.TestCoverage.Lines createOptetTypeTestCoverageLines() {
        return new OptetType.TestCoverage.Lines();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage.Blocks }
     * 
     */
    public OptetType.TestCoverage.Blocks createOptetTypeTestCoverageBlocks() {
        return new OptetType.TestCoverage.Blocks();
    }

    /**
     * Create an instance of {@link OptetType.TestCoverage.Instructions }
     * 
     */
    public OptetType.TestCoverage.Instructions createOptetTypeTestCoverageInstructions() {
        return new OptetType.TestCoverage.Instructions();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "optet")
    public JAXBElement<OptetType> createOptet(OptetType value) {
        return new JAXBElement<OptetType>(_Optet_QNAME, OptetType.class, null, value);
    }

}
