//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.31 at 04:40:48 PM CEST 
//


package com.thalesgroup.optet.common.jaxb.optet;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for optetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="optetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="testCoverage">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="classes">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="totalClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="coveredClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="methods">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="totalMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="coveredMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="lines">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="totalLines" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="coveredLines" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="blocks">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="totalBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="coveredBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="instructions">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="totalInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="coveredInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testResults">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="testResult" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="errors" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="failures" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="ignored" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="ok" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="undefined" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="metrics">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="metric" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="audits">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="file" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="violation" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="tool" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="recommandation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "optetType", propOrder = {
    "testCoverage",
    "testResults",
    "metrics",
    "audits"
})
public class OptetType {

    @XmlElement(required = true)
    protected OptetType.TestCoverage testCoverage;
    @XmlElement(required = true)
    protected OptetType.TestResults testResults;
    @XmlElement(required = true)
    protected OptetType.Metrics metrics;
    @XmlElement(required = true)
    protected OptetType.Audits audits;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the testCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link OptetType.TestCoverage }
     *     
     */
    public OptetType.TestCoverage getTestCoverage() {
        return testCoverage;
    }

    /**
     * Sets the value of the testCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptetType.TestCoverage }
     *     
     */
    public void setTestCoverage(OptetType.TestCoverage value) {
        this.testCoverage = value;
    }

    /**
     * Gets the value of the testResults property.
     * 
     * @return
     *     possible object is
     *     {@link OptetType.TestResults }
     *     
     */
    public OptetType.TestResults getTestResults() {
        return testResults;
    }

    /**
     * Sets the value of the testResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptetType.TestResults }
     *     
     */
    public void setTestResults(OptetType.TestResults value) {
        this.testResults = value;
    }

    /**
     * Gets the value of the metrics property.
     * 
     * @return
     *     possible object is
     *     {@link OptetType.Metrics }
     *     
     */
    public OptetType.Metrics getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptetType.Metrics }
     *     
     */
    public void setMetrics(OptetType.Metrics value) {
        this.metrics = value;
    }

    /**
     * Gets the value of the audits property.
     * 
     * @return
     *     possible object is
     *     {@link OptetType.Audits }
     *     
     */
    public OptetType.Audits getAudits() {
        return audits;
    }

    /**
     * Sets the value of the audits property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptetType.Audits }
     *     
     */
    public void setAudits(OptetType.Audits value) {
        this.audits = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="file" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="violation" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="tool" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="recommandation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file"
    })
    public static class Audits {

        protected List<OptetType.Audits.File> file;

        /**
         * Gets the value of the file property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the file property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptetType.Audits.File }
         * 
         * 
         */
        public List<OptetType.Audits.File> getFile() {
            if (file == null) {
                file = new ArrayList<OptetType.Audits.File>();
            }
            return this.file;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="violation" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="tool" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="recommandation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "violation"
        })
        public static class File {

            protected List<OptetType.Audits.File.Violation> violation;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the violation property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the violation property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getViolation().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OptetType.Audits.File.Violation }
             * 
             * 
             */
            public List<OptetType.Audits.File.Violation> getViolation() {
                if (violation == null) {
                    violation = new ArrayList<OptetType.Audits.File.Violation>();
                }
                return this.violation;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="tool" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="ruleset" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="recommandation" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Violation {

                @XmlAttribute(name = "tool")
                protected String tool;
                @XmlAttribute(name = "line")
                protected Integer line;
                @XmlAttribute(name = "severity")
                protected String severity;
                @XmlAttribute(name = "ruleset")
                protected String ruleset;
                @XmlAttribute(name = "message")
                protected String message;
                @XmlAttribute(name = "recommandation")
                protected String recommandation;
                @XmlAttribute(name = "source")
                protected String source;

                /**
                 * Gets the value of the tool property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTool() {
                    return tool;
                }

                /**
                 * Sets the value of the tool property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTool(String value) {
                    this.tool = value;
                }

                /**
                 * Gets the value of the line property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getLine() {
                    return line;
                }

                /**
                 * Sets the value of the line property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setLine(Integer value) {
                    this.line = value;
                }

                /**
                 * Gets the value of the severity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSeverity() {
                    return severity;
                }

                /**
                 * Sets the value of the severity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSeverity(String value) {
                    this.severity = value;
                }

                /**
                 * Gets the value of the ruleset property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRuleset() {
                    return ruleset;
                }

                /**
                 * Sets the value of the ruleset property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRuleset(String value) {
                    this.ruleset = value;
                }

                /**
                 * Gets the value of the message property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMessage() {
                    return message;
                }

                /**
                 * Sets the value of the message property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMessage(String value) {
                    this.message = value;
                }

                /**
                 * Gets the value of the recommandation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRecommandation() {
                    return recommandation;
                }

                /**
                 * Sets the value of the recommandation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRecommandation(String value) {
                    this.recommandation = value;
                }

                /**
                 * Gets the value of the source property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSource() {
                    return source;
                }

                /**
                 * Sets the value of the source property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSource(String value) {
                    this.source = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="metric" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "metric"
    })
    public static class Metrics {

        protected List<OptetType.Metrics.Metric> metric;

        /**
         * Gets the value of the metric property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the metric property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMetric().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptetType.Metrics.Metric }
         * 
         * 
         */
        public List<OptetType.Metrics.Metric> getMetric() {
            if (metric == null) {
                metric = new ArrayList<OptetType.Metrics.Metric>();
            }
            return this.metric;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Metric {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "result")
            protected String result;
            @XmlAttribute(name = "type")
            protected String type;
            @XmlAttribute(name = "category")
            protected String category;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResult(String value) {
                this.result = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            /**
             * Gets the value of the category property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCategory() {
                return category;
            }

            /**
             * Sets the value of the category property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCategory(String value) {
                this.category = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="classes">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="totalClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="coveredClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="methods">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="totalMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="coveredMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="lines">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="totalLines" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="coveredLines" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="blocks">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="totalBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="coveredBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="instructions">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="totalInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="coveredInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classes",
        "methods",
        "lines",
        "blocks",
        "instructions"
    })
    public static class TestCoverage {

        @XmlElement(required = true)
        protected OptetType.TestCoverage.Classes classes;
        @XmlElement(required = true)
        protected OptetType.TestCoverage.Methods methods;
        @XmlElement(required = true)
        protected OptetType.TestCoverage.Lines lines;
        @XmlElement(required = true)
        protected OptetType.TestCoverage.Blocks blocks;
        @XmlElement(required = true)
        protected OptetType.TestCoverage.Instructions instructions;

        /**
         * Gets the value of the classes property.
         * 
         * @return
         *     possible object is
         *     {@link OptetType.TestCoverage.Classes }
         *     
         */
        public OptetType.TestCoverage.Classes getClasses() {
            return classes;
        }

        /**
         * Sets the value of the classes property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetType.TestCoverage.Classes }
         *     
         */
        public void setClasses(OptetType.TestCoverage.Classes value) {
            this.classes = value;
        }

        /**
         * Gets the value of the methods property.
         * 
         * @return
         *     possible object is
         *     {@link OptetType.TestCoverage.Methods }
         *     
         */
        public OptetType.TestCoverage.Methods getMethods() {
            return methods;
        }

        /**
         * Sets the value of the methods property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetType.TestCoverage.Methods }
         *     
         */
        public void setMethods(OptetType.TestCoverage.Methods value) {
            this.methods = value;
        }

        /**
         * Gets the value of the lines property.
         * 
         * @return
         *     possible object is
         *     {@link OptetType.TestCoverage.Lines }
         *     
         */
        public OptetType.TestCoverage.Lines getLines() {
            return lines;
        }

        /**
         * Sets the value of the lines property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetType.TestCoverage.Lines }
         *     
         */
        public void setLines(OptetType.TestCoverage.Lines value) {
            this.lines = value;
        }

        /**
         * Gets the value of the blocks property.
         * 
         * @return
         *     possible object is
         *     {@link OptetType.TestCoverage.Blocks }
         *     
         */
        public OptetType.TestCoverage.Blocks getBlocks() {
            return blocks;
        }

        /**
         * Sets the value of the blocks property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetType.TestCoverage.Blocks }
         *     
         */
        public void setBlocks(OptetType.TestCoverage.Blocks value) {
            this.blocks = value;
        }

        /**
         * Gets the value of the instructions property.
         * 
         * @return
         *     possible object is
         *     {@link OptetType.TestCoverage.Instructions }
         *     
         */
        public OptetType.TestCoverage.Instructions getInstructions() {
            return instructions;
        }

        /**
         * Sets the value of the instructions property.
         * 
         * @param value
         *     allowed object is
         *     {@link OptetType.TestCoverage.Instructions }
         *     
         */
        public void setInstructions(OptetType.TestCoverage.Instructions value) {
            this.instructions = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="totalBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="coveredBlocks" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Blocks {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "totalBlocks")
            protected Integer totalBlocks;
            @XmlAttribute(name = "coveredBlocks")
            protected Integer coveredBlocks;
            @XmlAttribute(name = "pourcentage")
            protected Double pourcentage;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the totalBlocks property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalBlocks() {
                return totalBlocks;
            }

            /**
             * Sets the value of the totalBlocks property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalBlocks(Integer value) {
                this.totalBlocks = value;
            }

            /**
             * Gets the value of the coveredBlocks property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCoveredBlocks() {
                return coveredBlocks;
            }

            /**
             * Sets the value of the coveredBlocks property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCoveredBlocks(Integer value) {
                this.coveredBlocks = value;
            }

            /**
             * Gets the value of the pourcentage property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPourcentage() {
                return pourcentage;
            }

            /**
             * Sets the value of the pourcentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPourcentage(Double value) {
                this.pourcentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="totalClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="coveredClasses" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Classes {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "totalClasses")
            protected Integer totalClasses;
            @XmlAttribute(name = "coveredClasses")
            protected Integer coveredClasses;
            @XmlAttribute(name = "pourcentage")
            protected Double pourcentage;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the totalClasses property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalClasses() {
                return totalClasses;
            }

            /**
             * Sets the value of the totalClasses property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalClasses(Integer value) {
                this.totalClasses = value;
            }

            /**
             * Gets the value of the coveredClasses property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCoveredClasses() {
                return coveredClasses;
            }

            /**
             * Sets the value of the coveredClasses property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCoveredClasses(Integer value) {
                this.coveredClasses = value;
            }

            /**
             * Gets the value of the pourcentage property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPourcentage() {
                return pourcentage;
            }

            /**
             * Sets the value of the pourcentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPourcentage(Double value) {
                this.pourcentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="totalInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="coveredInstructions" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Instructions {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "totalInstructions")
            protected Integer totalInstructions;
            @XmlAttribute(name = "coveredInstructions")
            protected Integer coveredInstructions;
            @XmlAttribute(name = "pourcentage")
            protected Double pourcentage;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the totalInstructions property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalInstructions() {
                return totalInstructions;
            }

            /**
             * Sets the value of the totalInstructions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalInstructions(Integer value) {
                this.totalInstructions = value;
            }

            /**
             * Gets the value of the coveredInstructions property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCoveredInstructions() {
                return coveredInstructions;
            }

            /**
             * Sets the value of the coveredInstructions property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCoveredInstructions(Integer value) {
                this.coveredInstructions = value;
            }

            /**
             * Gets the value of the pourcentage property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPourcentage() {
                return pourcentage;
            }

            /**
             * Sets the value of the pourcentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPourcentage(Double value) {
                this.pourcentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="totalLines" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="coveredLines" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Lines {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "totalLines")
            protected Integer totalLines;
            @XmlAttribute(name = "coveredLines")
            protected Integer coveredLines;
            @XmlAttribute(name = "pourcentage")
            protected Double pourcentage;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the totalLines property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalLines() {
                return totalLines;
            }

            /**
             * Sets the value of the totalLines property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalLines(Integer value) {
                this.totalLines = value;
            }

            /**
             * Gets the value of the coveredLines property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCoveredLines() {
                return coveredLines;
            }

            /**
             * Sets the value of the coveredLines property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCoveredLines(Integer value) {
                this.coveredLines = value;
            }

            /**
             * Gets the value of the pourcentage property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPourcentage() {
                return pourcentage;
            }

            /**
             * Sets the value of the pourcentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPourcentage(Double value) {
                this.pourcentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="totalMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="coveredMethods" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="pourcentage" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Methods {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "totalMethods")
            protected Integer totalMethods;
            @XmlAttribute(name = "coveredMethods")
            protected Integer coveredMethods;
            @XmlAttribute(name = "pourcentage")
            protected Double pourcentage;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the totalMethods property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTotalMethods() {
                return totalMethods;
            }

            /**
             * Sets the value of the totalMethods property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTotalMethods(Integer value) {
                this.totalMethods = value;
            }

            /**
             * Gets the value of the coveredMethods property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCoveredMethods() {
                return coveredMethods;
            }

            /**
             * Sets the value of the coveredMethods property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCoveredMethods(Integer value) {
                this.coveredMethods = value;
            }

            /**
             * Gets the value of the pourcentage property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getPourcentage() {
                return pourcentage;
            }

            /**
             * Sets the value of the pourcentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setPourcentage(Double value) {
                this.pourcentage = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="testResult" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="errors" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="failures" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="ignored" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="ok" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="undefined" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testResult"
    })
    public static class TestResults {

        protected List<OptetType.TestResults.TestResult> testResult;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "errors")
        protected BigInteger errors;
        @XmlAttribute(name = "failures")
        protected BigInteger failures;
        @XmlAttribute(name = "ignored")
        protected BigInteger ignored;
        @XmlAttribute(name = "ok")
        protected BigInteger ok;
        @XmlAttribute(name = "undefined")
        protected BigInteger undefined;

        /**
         * Gets the value of the testResult property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the testResult property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTestResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptetType.TestResults.TestResult }
         * 
         * 
         */
        public List<OptetType.TestResults.TestResult> getTestResult() {
            if (testResult == null) {
                testResult = new ArrayList<OptetType.TestResults.TestResult>();
            }
            return this.testResult;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the errors property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getErrors() {
            return errors;
        }

        /**
         * Sets the value of the errors property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setErrors(BigInteger value) {
            this.errors = value;
        }

        /**
         * Gets the value of the failures property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFailures() {
            return failures;
        }

        /**
         * Sets the value of the failures property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFailures(BigInteger value) {
            this.failures = value;
        }

        /**
         * Gets the value of the ignored property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIgnored() {
            return ignored;
        }

        /**
         * Sets the value of the ignored property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIgnored(BigInteger value) {
            this.ignored = value;
        }

        /**
         * Gets the value of the ok property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOk() {
            return ok;
        }

        /**
         * Sets the value of the ok property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOk(BigInteger value) {
            this.ok = value;
        }

        /**
         * Gets the value of the undefined property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUndefined() {
            return undefined;
        }

        /**
         * Sets the value of the undefined property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUndefined(BigInteger value) {
            this.undefined = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class TestResult {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "result")
            protected String result;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the result property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResult() {
                return result;
            }

            /**
             * Sets the value of the result property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResult(String value) {
                this.result = value;
            }

        }

    }

}
